/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://jyifycun6bf4bjkh6dzmomiz2m.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5z55rnm3gbam7kikvq6wjsie4a",
    "aws_cognito_identity_pool_id": "us-west-2:b9d8398f-a047-45b3-9d9d-601d15e850e8",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_5dzjpZD6u",
    "aws_user_pools_web_client_id": "4skereplin789gdjs38pjv80n7",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "HTTPProtocol",
            "endpoint": "https://xub8b9pnof.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
